### ISSUE TITLE
七牛云配置有例子给我们参考下吗

### ISSUE THREAD

**Issue by scychina** [shaonianzhentan/ha_file_explorer#18]
七牛云配置有例子给我们参考下吗？我找了好一会没找到配置地方

**Comment by shaonianzhentan** [comment]
> 七牛云配置有例子给我们参考下吗？我找了好一会没找到配置地方

在服务里进行配置，有参数介绍，如果你使用过七牛云，参数应该很容易理解

**Comment by scychina** [comment]
> > 七牛云配置有例子给我们参考下吗？我找了好一会没找到配置地方
> 
> 在服务里进行配置，有参数介绍，如果你使用过七牛云，参数应该很容易理解

好的谢谢
