### ISSUE TITLE
备份HA根目录

### ISSUE THREAD

**Issue by qiuyuxuan1999** [shaonianzhentan/ha_file_explorer#19]
之前的插件是可以备份整个HA的根目录的（当然大文件会跳过），但新版本插件没法备份根目录了，只能进入类似www这样的二级目录后有选项可以备份该目录。
是否有方法可以备份整个HA根目录？谢谢！

**Comment by shaonianzhentan** [comment]
> 之前的插件是可以备份整个HA的根目录的（当然大文件会跳过），但新版本插件没法备份根目录了，只能进入类似www这样的二级目录后有选项可以备份该目录。
> 是否有方法可以备份整个HA根目录？谢谢！

调用`ha_file_explorer.upload`服务，可以上传整个根目录
- 强制过滤了 ‘home-assistant_v2.db', 'home-assistant.log', 'deps', 'media', 'core'

当然也可以自己过滤根目录的指定文件

**Comment by qiuyuxuan1999** [comment]
> > 之前的插件是可以备份整个HA的根目录的（当然大文件会跳过），但新版本插件没法备份根目录了，只能进入类似www这样的二级目录后有选项可以备份该目录。
> > 是否有方法可以备份整个HA根目录？谢谢！
> 
> 调用`ha_file_explorer.upload`服务，可以上传整个根目录
> 
> * 强制过滤了 ‘home-assistant_v2.db', 'home-assistant.log', 'deps', 'media', 'core'
> 
> 当然也可以自己过滤根目录的指定文件

原来在这里啊，找到了，谢谢啦。
