### ISSUE TITLE
“github的域名解析、修改hacs的资源下载链接”按钮都修改了哪些文件？

### ISSUE THREAD

**Issue by qiuyuxuan1999** [shaonianzhentan/ha_file_explorer#22]
大佬，谢谢你的文件管理插件，我之前点过您的插件里的“github的域名解析、修改hacs的资源下载链接”按钮，我以为这会修改/custom_components/hacs/helpers/function/download.py这个文件以及主机hosts文件，但发现并没有修改，hacs倒是可以下载了，但是有几个需要联网抓取信息的集成变得报错了，不知道跟点这项按钮有没有关系，我想知道这项按钮都修改了哪些文件，怎样能改回来，谢谢。

**Comment by shaonianzhentan** [comment]
因为你是在docker环境中运行的，估计是改了docker里的hosts
