### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by whowho182** [shaonianzhentan/ha_file_explorer#23]
The following integrations and platforms could not be set up:
ha_file_explorer

Logger: homeassistant.setup
Source: setup.py:172
First occurred: 上午8:41:34 (1 occurrences)
Last logged: 上午8:41:34
Setup failed for ha_file_explorer: Integration not found.

版本 | core-2021.5.0.dev20210421
安装类型 | Home Assistant Container

**Comment by shaonianzhentan** [comment]
这个组件没有找到，估计是与旧版HA不兼容，建议升级HA到最新版本

**Comment by whowho182** [comment]
2.7版本没问题了，速度真快，谢谢。
