### ISSUE TITLE
集成安装错误

### ISSUE THREAD

**Issue by whowho182** [shaonianzhentan/ha_file_explorer#24]
集成安装，怎么提示无法加载配置向导。版本（core-2021.5.0.dev20210421）

**Comment by 2478622331** [comment]
一样的问题 版本2021.7.0.dev20210530

**Comment by shaonianzhentan** [comment]
请将 HomeAssistant 升级到最新版

**Comment by whowho182** [comment]
谢谢回复，升级后登陆不上了大神，参考你的视频教程升级的一切正常，可就是登不上发自我的华为手机-------- 原始邮件 --------发件人： Monkey • D • Code ***@***.***>日期： 2022年1月6日周四 半夜12:14收件人： shaonianzhentan/ha_file_explorer ***@***.***>抄送： whowho182 ***@***.***>, Author ***@***.***>主    题： Re: [shaonianzhentan/ha_file_explorer] 集成安装错误 (Issue #24)

请将 HomeAssistant 升级到最新版

**Comment by shaonianzhentan** [comment]
最好贴个图，或发一下错误日志

**Comment by whowho182** [comment]
谢谢回复，大神。可以了，用命令启动了。有问题再麻烦您。发自我的华为手机-------- 原始邮件 --------发件人： Monkey • D • Code ***@***.***>日期： 2022年1月10日周一 上午9:51收件人： shaonianzhentan/ha_file_explorer ***@***.***>抄送： whowho182 ***@***.***>, Author ***@***.***>主    题： Re: [shaonianzhentan/ha_file_explorer] 集成安装错误 (Issue #24)

最好贴个图，或发一下错误日志

**Comment by openwrt-try** [comment]
具体怎么解决呀，我也是这个问题，Home Assistant 2022.2.0.dev20220115
您想要配置 ha_file_explorer 吗？
无法加载配置向导

Logger: homeassistant.config_entries
Source: config_entries.py:725
First occurred: 21:46:54 (1 occurrences)
Last logged: 21:46:54

Cannot find integration ha_file_explorer

**Comment by whowho182** [comment]
看作者教程，升级docker下Ha镜像，然后就可以集成安装了发自我的手机-------- 原始邮件 --------发件人： openwrt-try ***@***.***>日期： 2022年1月15日周六 晚上9:51收件人： shaonianzhentan/ha_file_explorer ***@***.***>抄送： whowho182 ***@***.***>, Author ***@***.***>主    题： Re: [shaonianzhentan/ha_file_explorer] 集成安装错误 (Issue #24)

具体怎么解决呀，我也是这个问题，Home Assistant 2022.2.0.dev20220115

您想要配置 ha_file_explorer 吗？

无法加载配置向导

Logger: homeassistant.config_entries

Source: config_entries.py:725

First occurred: 21:46:54 (1 occurrences)

Last logged: 21:46:54

Cannot find integration ha_file_explorer

**Comment by openwrt-try** [comment]
我的已经是最新版了，还是无法安装，不知道能不能像hacs那样下载配置文件安装

**Comment by whowho182** [comment]
发自我的手机-------- 原始邮件 --------发件人： openwrt-try ***@***.***>日期： 2022年1月16日周日 晚上7:12收件人： shaonianzhentan/ha_file_explorer ***@***.***>抄送： whowho182 ***@***.***>, Author ***@***.***>主    题： Re: [shaonianzhentan/ha_file_explorer] 集成安装错误 (Issue #24)

我的已经是最新版了，还是无法安装，不知道能不能像hacs那样下载配置文件安装
