### ISSUE TITLE
请问，能不能像hacs那样下载配置文件安装呀，在线安装显示无法加载配置向导

### ISSUE THREAD

**Issue by openwrt-try** [shaonianzhentan/ha_file_explorer#25]
Home Assistant 2022.2.0.dev20220115，已经是最新版了
安装的时候显示如下问题，

您想要配置 ha_file_explorer 吗？
无法加载配置向导

Logger: homeassistant.config_entries
Source: config_entries.py:725
First occurred: 21:46:54 (1 occurrences)
Last logged: 21:46:54

Cannot find integration ha_file_explorer

**Comment by shaonianzhentan** [comment]
应该是相关依赖没有安装成功，网络的问题
