### ISSUE TITLE
备份的目录是否需要选择？是把hass全部内容备份吗

### ISSUE THREAD

**Issue by hejie127** [shaonianzhentan/ha_file_explorer#28]
来鸭大神好，完全按照公众号教程做的备份，通知也显示正在压缩上传备份，但是文件管理-备份里没有任何东西。

请问备份的内容是自动选择的吗，不需要手动干预？是把hass全部内容备份吗？

**Comment by shaonianzhentan** [comment]
如果配置都正确，应该会有成功的通知提示。
如果没有最好看一下日志是否有相关错误信息

**Comment by hejie127** [comment]
来鸭大神好，点备份后会收到“文件管理-开始压缩上传备份文件”。这个通知，别的没有。

跟踪自动化会有以下日志。
Executed: 2022年2月18日 20:41:38
Result:
params:
  domain: ha_file_explorer
  service: upload
  service_data: {}
  target: {}
running_script: false
limit: 10

**Comment by shaonianzhentan** [comment]
你可以先备份单个文件试试，如果能成功说明功能没问题
