### ISSUE TITLE
custom components文件夹无法备份

### ISSUE THREAD

**Issue by ghostist** [shaonianzhentan/ha_file_explorer#3]
这个文件夹包含了一些第三方插件
如：ha_file_explorer（手动狗头）
不备份这个文件夹  则系统崩了后不好恢复...
希望大文件筛选可以避免这个文件夹（以及其他HA默认文件夹）

**Comment by shaonianzhentan** [comment]
这个可以单独备份啊，在文件管理列表选项里

**Comment by ghostist** [comment]
明白了 还有这个路径
现在目录排序默认好像是按照文件（夹）修改时间排序的，有没有办法按照名称排序？名称找起来文件更快一点
HA根目录查看，文件夹在上，文件在下
