### ISSUE TITLE
v2.7.6 无法加载配置向导: undefined

### ISSUE THREAD

**Issue by liupcoder** [shaonianzhentan/ha_file_explorer#31]
![image](https://user-images.githubusercontent.com/49053793/167389235-afe04267-1177-4fe9-8a43-b32f1f44d5da.png)
![image](https://user-images.githubusercontent.com/49053793/167389401-346fb4e4-f602-4e1b-9cbe-493aec5338ec.png)

**Comment by shaonianzhentan** [comment]
你下载dev版本吧
https://github.com/shaonianzhentan/ha_file_explorer/tree/dev

**Comment by liupcoder** [comment]
强
