### ISSUE TITLE
armbian bullseye 非docker 版本homeassistant 提示不支持通过 UI 配置

### ISSUE THREAD

**Issue by openwrt-try** [shaonianzhentan/ha_file_explorer#33]
此集成不支持通过 UI 配置。如果您是从 Home Assistant 网站点击链接前来，请确保您运行的是最新版本的 Home Assistant。

大神能解决不呀，谢谢啦

**Comment by shaonianzhentan** [comment]
手动下载dev的版本安装

**Comment by openwrt-try** [comment]
> 手动下载dev的版本安装

大神，通过
curl https://gitee.com/shaonianzhentan/ha_file_explorer/raw/dev/bash/install.sh | bash
安装后文件夹里有ha_file_explorer了，在homeassistant的集成里搜索ha_file_explorer，点击添加，还是提示上述错误
homeassistant也重启了，

**Comment by shaonianzhentan** [comment]
该不是你的HA版本太旧了吧

**Comment by openwrt-try** [comment]
> 该不是你的HA版本太旧了吧

Home Assistant Core 2022.5.4
我是用玩客云装的armbian bullseye，直接系统服务形式安装的homeassistant，，估计是什么依赖没装好吧
小白实在是搞不懂，
