### ISSUE TITLE
报错：Flow handler not found for entry 文件管理 for ha_file_explorer

### ISSUE THREAD

**Issue by qiuyuxuan1999** [shaonianzhentan/ha_file_explorer#34]
大佬，我切换到dev分支手动下载代码覆盖旧版代码，重启HA后，插件报错无法使用：
Logger: homeassistant.config_entries
Source: config_entries.py:497
First occurred: 11:20:54 (1 occurrences)
Last logged: 11:20:54

Flow handler not found for entry 文件管理 for ha_file_explorer

我的HA的版本：
System Health

version: core-2021.9.7
installation_type: Home Assistant Core
dev: false
hassio: false
docker: false
user: sc-homeassistant
virtualenv: true
python_version: 3.8.12
os_name: Linux
os_version: 3.10.105
arch: armv7l
timezone: Asia/Shangha

**Comment by shaonianzhentan** [comment]
dev版本只支持今年5月份及以后的版本

**Comment by qiuyuxuan1999** [comment]
晓得了 多谢大佬
