### ISSUE TITLE
Home Assistant Core 2022.6.5下无法使用

### ISSUE THREAD

**Issue by HonestQiao** [shaonianzhentan/ha_file_explorer#38]
<img width="519" alt="iShot_2022-06-14_08 25 58" src="https://user-images.githubusercontent.com/696708/173468657-36315768-6a3b-4819-9d3e-e9ec878d0963.png">

<img width="613" alt="iShot_2022-06-14_08 27 30" src="https://user-images.githubusercontent.com/696708/173468776-76274230-7abb-4394-ac5d-57d2c5da6042.png">

<img width="475" alt="iShot_2022-06-14_08 24 51" src="https://user-images.githubusercontent.com/696708/173468675-49e9b2c8-6b16-45bb-ac4a-5a336f0d0267.png">

<img width="650" alt="iShot_2022-06-14_08 24 58" src="https://user-images.githubusercontent.com/696708/173468786-e4c3d335-5d44-438d-b2f2-4d2bde34b132.png">

<img width="394" alt="iShot_2022-06-14_08 25 08" src="https://user-images.githubusercontent.com/696708/173468793-484a0223-77ae-47ed-a3c6-4e79cb1af4f3.png">

**Comment by shaonianzhentan** [comment]
你没将代码放到自定义组件目录中吗？

**Comment by longavailable** [comment]
Home Assistant Core 2022.6.6 同样问题。

是通过hacs安装的。也检查了，ha_file_explorer是在custom_components路径下。@shaonianzhentan 

logs中没有任何相关提醒。
