### ISSUE TITLE
Home Assistant Core 2022.7.0.dev0 下无法使用

### ISSUE THREAD

**Issue by q1uTruth** [shaonianzhentan/ha_file_explorer#41]
通过命令安装 或者 直接拷贝文件
都会出现这个错误信息
![image](https://user-images.githubusercontent.com/54021876/177032109-a8a5a135-f8ab-4c8d-9aea-5cdfd60cec36.png)
![image](https://user-images.githubusercontent.com/54021876/177032126-c875ec24-09d5-4224-88b9-02d32f72ef61.png)

**Comment by shaonianzhentan** [comment]
可以参考微信公众号的安装教程，或提供相关日志
