### ISSUE TITLE
侧边栏的云备份，要怎样才能使用

### ISSUE THREAD

**Issue by Seifon** [shaonianzhentan/ha_file_explorer#42]
我配置了七牛的密钥，但侧边栏的云备份，还是不显示内容。

想问一下，是不是还要装什么插件？

**Comment by shaonianzhentan** [comment]
新版本没有备份功能了

**Comment by Seifon** [comment]
> 新版本没有备份功能了

这个功能感觉挺有用的，为什么要去掉啊

**Comment by shaonianzhentan** [comment]
> > 新版本没有备份功能了
> 
> 这个功能感觉挺有用的，为什么要去掉啊

因为HA已经有备份功能了

**Comment by Seifon** [comment]
> > > 新版本没有备份功能了
> > 
> > 
> > 这个功能感觉挺有用的，为什么要去掉啊
> 
> 因为HA已经有备份功能了

但是没有备份到七牛云的功能额
