### ISSUE TITLE
提示：此集成不支持通过 UI 配置，应该怎么处理呢

### ISSUE THREAD

**Issue by Seifon** [shaonianzhentan/ha_file_explorer#43]
错误
此集成不支持通过 UI 配置。如果您是从 Home Assistant 网站点击链接前来，请确保您运行的是最新版本的 Home Assistant。

HA版本：2022.9.4

**Comment by huaxiuyiwei** [comment]
也遇到一样的问题了

**Comment by zealotCE** [comment]
相同问题，应该如何解决呢？
