### ISSUE TITLE
老版本中的修改完YAML文件后有一个菜单可以直接重启

### ISSUE THREAD

**Issue by y306702588** [shaonianzhentan/ha_file_explorer#45]
老版本中的修改完YAML文件后有一个菜单可以直接重启，新版本里没有了，感觉这个功能还是蛮实用的，可以不用去切换到系统自带的重启菜单就能快速的重启，新版里还可以再加上这个菜单嘛？

**Comment by shaonianzhentan** [comment]
新版本在右上角，在命令中可以搜索HA的所有服务（包括重启）
![image](https://user-images.githubusercontent.com/5294022/195991325-f3e83bfe-8896-4183-8cd5-adf2c5c6bf93.png)

**Comment by y306702588** [comment]
好的，按你的提示已经找到了，谢谢了！
