### ISSUE TITLE
更新2023.4.X后无法显示文件管理器界面  空白的

### ISSUE THREAD

**Issue by gzzyyt** [shaonianzhentan/ha_file_explorer#48]
更新2023.4.X后无法显示文件管理器界面  空白的
![QQ截图20230409215327](https://user-images.githubusercontent.com/25847375/230776769-e700ab5d-2885-4ded-b0c1-fbe398abb722.png)
![QQ截图20230409215341](https://user-images.githubusercontent.com/25847375/230776780-33294bfd-19f6-455e-991a-cc8d179a86d6.png)

**Comment by gzzyyt** [comment]
@shaonianzhentan 麻烦您看下，能否修复下

**Comment by shaonianzhentan** [comment]
应该已经好了

**Comment by gzzyyt** [comment]
@shaonianzhentan 这边测试还是不行，目前版本是2023.5.2最新版
![image](https://user-images.githubusercontent.com/25847375/236596534-f8747a4f-96a8-44e0-919a-73b45f4c403f.png)
![image](https://user-images.githubusercontent.com/25847375/236596543-955edfc2-1b6a-4dda-9117-0b5a4ce20597.png)

**Comment by shaonianzhentan** [comment]
应该是主题问题，请重置默认主题
