### ISSUE TITLE
没有 二级菜单看不到文件 请问怎么处理谢谢 

### ISSUE THREAD

**Issue by yhwl8888** [shaonianzhentan/ha_file_explorer#5]
![image](https://user-images.githubusercontent.com/48284412/88481489-65e47c80-cf8e-11ea-80cb-199d009bcfeb.png)

**Comment by shaonianzhentan** [comment]
你要不贴个日志出来吧，或是你自己检测下日志，看看有没有什么错误之类的
就一张图我也看不来啥
