### ISSUE TITLE
文件管理器界面404: Not Found

### ISSUE THREAD

**Issue by petena** [shaonianzhentan/ha_file_explorer#50]
![image](https://github.com/shaonianzhentan/ha_file_explorer/assets/54195125/a30dd0c0-5176-47a7-a84e-c91b3b10f761)
HA版本
![image](https://github.com/shaonianzhentan/ha_file_explorer/assets/54195125/82e6e337-e81f-49f4-b46f-68ec89121fcf)

**Comment by shaonianzhentan** [comment]
应该是插件文件没下载完全，重新安装试试
