### ISSUE TITLE
add russian language

### ISSUE THREAD

**Issue by ananyevgv** [shaonianzhentan/ha_file_explorer#51]
AppLayout.8c51d382.js

ru:{name:"Файловый менеджер",file:"файл",folder:"папка",upload:"загрузить",add:"добавить",delete:"удалить",rename:"переименовать",edit:"правка",browse:"просмотр",entities:"объект",command:"команда",save:"сохранить",cancel:"отменить",confirm:"потвердить",currentName:"Текушее имя",uploadTips:"Примечание: файлы с таким же именем будут перезаписаны",newName(e){return`New ${e} Name`},deleteConfirm(e){return`ОК, чтобы удалить этот файл \u3010${e}\u3011\uFF1F`}}

ru.json
{
    "title": "Файловый менеджер",
    "config": {
        "step": {
            "user": {
                "description": "",
                "data": {
                    "require_admin": "Виден только администраторам"
                }
            }
        },
        "error": {},
        "abort": {
            "single_instance_allowed": "Разрешен единственный экземпляр."
        }
    }
}

**Comment by shaonianzhentan** [comment]
Already added

**Comment by ananyevgv** [comment]
谢谢
