### ISSUE TITLE
hassio supervisor 

### ISSUE THREAD

**Issue by mildrabbit** [shaonianzhentan/ha_file_explorer#7]
楼主你好，我的HA的系统是hassio,就是集成了supervisor 的，他的系统也是docker运行，进行到docker后发现他没有python环境。。要如何安装本插件呢？

**Comment by shaonianzhentan** [comment]
建议你使用hassio系统自带的文件编辑器插件

**Comment by mildrabbit** [comment]
我是看上了他提取github的功能，太好用了。
